from typing import Optional

from pydantic import Field, BaseModel


class BrokerPosition(BaseModel):
    positionIdx: Optional[int] = Field(default=None)
    category: Optional[int] = Field(default=None)
    riskId: Optional[str] = Field(default=None)
    riskLimitValue: Optional[str] = Field(default=None)
    symbol: Optional[str] = Field(default=None)
    side: Optional[str] = Field(default=None)
    size: Optional[str] = Field(default=None)
    avgPrice: Optional[str] = Field(default=None)
    positionValue: Optional[str] = Field(default=None)
    tradeMode: Optional[int] = Field(default=None)
    autoAddMargin: Optional[int] = Field(default=None)
    positionStatus: Optional[str] = Field(default=None)
    leverage: Optional[str] = Field(default=None)
    markPrice: Optional[str] = Field(default=None)
    liqPrice: Optional[str] = Field(default=None)
    bustPrice: Optional[str] = Field(default=None)
    positionMM: Optional[str] = Field(default=None)
    positionBalance: Optional[str] = Field(default=None)
    takeProfit: Optional[str] = Field(default=None)
    stopLoss: Optional[str] = Field(default=None)
    trailingStop: Optional[str] = Field(default=None)
    sessionAvgPrice: Optional[str] = Field(default=None)
    unrealisedPnl: Optional[str] = Field(default=None)
    curRealisedPnl: Optional[str] = Field(default=None)
    cumRealisedPnl: Optional[str] = Field(default=None)
    adlRankIndicator: Optional[int] = Field(default=None)
    createdTIme: Optional[str] = Field(default=None)
    updatedTime: Optional[str] = Field(default=None)
    seq: Optional[float] = Field(default=None)
    isReduceOnly: Optional[bool] = Field(default=None)
    mmrSysUpdatedTime: Optional[str] = Field(default=None)
    leverageSysUpdatedTime: Optional[str] = Field(default=None)
    tpslMode: Optional[str] = Field(default=None)