from enum import Enum


class LevelEnum(Enum):
    CENTRALBANKDEALERRANGE = "CBDR"
    EQHL = "EQHL"
    OPTIMALTRADEENTRY = "OTE"
    PREMIUMDISCOUNT = "PD"
    STANDARDDIVIATION = "STDV"
    NEWYORKDAILYOPENGAP = "NDOG"
    NEWYORKWEEKLYOPENGAP = "NWOG"
    PDLEVEL = "PDL"
    PWLEVEL = "PWL"
