from enum import Enum


class StructureEnum(Enum):
    BREAKOFSTRUCTURE = 'BOS'
    CHANGEINCHARACTER = 'CHOCH'
    CHANGEINSTATEOFDELIVERY = 'CISD'
    SMARTMONEYTECHNIQUE = 'SMT'
    MITIGATIONBLOCK = 'MB'